-- NOTE: This file is auto generated by ./sql-generator

-- FacePersonVerdictRepository.upsertPending
insert into
  "face_person_verdict" ("personId", "assetFaceId", "distance")
values
  ($1, $2, $3)
on conflict ("personId", "assetFaceId")
where
  "personId" is not null do update
set
  "distance" = "excluded"."distance",
  "updatedAt" = now()
where
  "face_person_verdict"."status" = $4

-- FacePersonVerdictRepository.resolveAssignedFace
delete from "face_person_verdict"
where
  "assetFaceId" = $1
  and "status" = $2

-- FacePersonVerdictRepository.upsertPendingForSpacePerson
insert into
  "face_person_verdict" ("spacePersonId", "assetFaceId", "distance")
values
  ($1, $2, $3)
on conflict ("spacePersonId", "assetFaceId")
where
  "spacePersonId" is not null do update
set
  "distance" = "excluded"."distance",
  "updatedAt" = now()
where
  "face_person_verdict"."status" = $4

-- FacePersonVerdictRepository.claimPending
delete from "face_person_verdict"
where
  "personId" = $1
  and "assetFaceId" = $2
  and "status" = $3

-- FacePersonVerdictRepository.claimPendingForSpacePerson
delete from "face_person_verdict"
where
  "spacePersonId" = $1
  and "assetFaceId" = $2
  and "status" = $3

-- FacePersonVerdictRepository.markRejected
insert into
  "face_person_verdict" (
    "personId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6)
on conflict ("personId", "assetFaceId")
where
  "personId" is not null do update
set
  "status" = $7,
  "identityId" = $8,
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.markIgnored
insert into
  "face_person_verdict" (
    "personId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6)
on conflict ("personId", "assetFaceId")
where
  "personId" is not null do update
set
  "status" = $7,
  "identityId" = $8,
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.markRejectedForSpacePerson
insert into
  "face_person_verdict" (
    "spacePersonId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6)
on conflict ("spacePersonId", "assetFaceId")
where
  "spacePersonId" is not null do update
set
  "status" = $7,
  "identityId" = $8,
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.markIgnoredForSpacePerson
insert into
  "face_person_verdict" (
    "spacePersonId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6)
on conflict ("spacePersonId", "assetFaceId")
where
  "spacePersonId" is not null do update
set
  "status" = $7,
  "identityId" = $8,
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.removeVerdicts
delete from "face_person_verdict"
where
  "id" in ($1)
  and "status" in ($2, $3)
returning
  "id"

-- FacePersonVerdictRepository.getNegativeVerdictTokens
select
  "assetFaceId",
  "personId",
  "spacePersonId",
  "identityId"
from
  "face_person_verdict"
where
  "assetFaceId" in ($1)
  and "status" in ($2, $3)

-- FacePersonVerdictRepository.getPendingForPerson
select
  "person"."id"
from
  "person"
where
  "person"."id" = $1
  and "person"."name" != $2
  and "person"."isHidden" = $3
  and "person"."type" = $4

-- FacePersonVerdictRepository.getPendingForSpacePerson
select
  "shared_space_person"."id"
from
  "shared_space_person"
  inner join "shared_space" on "shared_space"."id" = "shared_space_person"."spaceId"
where
  "shared_space_person"."id" = $1
  and "shared_space_person"."spaceId" = $2
  and BTRIM("shared_space_person"."name") <> $3
  and "shared_space_person"."isHidden" is false
  and "shared_space_person"."type" = $4
  and "shared_space"."faceRecognitionEnabled" is true

-- FacePersonVerdictRepository.hasPendingForSpacePerson
select
  "fpv"."assetFaceId"
from
  "face_person_verdict" as "fpv"
  inner join "shared_space_person" on "shared_space_person"."id" = "fpv"."spacePersonId"
  inner join "shared_space" on "shared_space"."id" = "shared_space_person"."spaceId"
  inner join "asset_face" as "af" on "af"."id" = "fpv"."assetFaceId"
  inner join "asset" on "asset"."id" = "af"."assetId"
where
  "fpv"."spacePersonId" = $1
  and "fpv"."assetFaceId" = $2
  and "fpv"."status" = $3
  and "fpv"."distance" > $4
  and "fpv"."distance" <= $5
  and "shared_space_person"."spaceId" = $6
  and BTRIM("shared_space_person"."name") <> $7
  and "shared_space_person"."isHidden" is false
  and "shared_space_person"."type" = $8
  and "shared_space"."faceRecognitionEnabled" is true
  and "af"."personId" is null
  and "af"."deletedAt" is null
  and "af"."isVisible" is true
  and "asset"."deletedAt" is null
  and "asset"."isOffline" is false
  and "asset"."visibility" in ($9, $10)
  and (
    exists (
      select
        1 as "exists"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset"."id"
        and "shared_space_asset"."spaceId" = $11::uuid
    )
    or exists (
      select
        1 as "exists"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = $12::uuid
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $13::uuid
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $14::uuid
      )
    )
  )
