-- NOTE: This file is auto generated by ./sql-generator

-- SessionRepository.get
select distinct
  "country"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
  and "country" is not null
  and "country" != $7
order by
  "country"
select distinct
  "make"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
  and "make" is not null
  and "make" != $7
order by
  "make"
WITH
  filtered_assets AS (
    (
      select
        "asset"."id"
      from
        "asset"
      where
        "asset"."visibility" = $1
        and "asset"."deletedAt" is null
        and (
          "asset"."ownerId" = any ($2::uuid[])
          or exists (
            select
            from
              "shared_space_asset"
            where
              "shared_space_asset"."assetId" = "asset"."id"
              and "shared_space_asset"."spaceId" = any ($3::uuid[])
          )
          or exists (
            select
            from
              "shared_space_library"
            where
              "shared_space_library"."libraryId" = "asset"."libraryId"
              and "shared_space_library"."spaceId" = any ($4::uuid[])
          )
        )
        and "asset"."fileCreatedAt" >= $5
    )
  ),
  identity_faces AS (
    SELECT DISTINCT
      face_identity_face."identityId"
    FROM
      face_identity_face
      INNER JOIN asset_face ON asset_face.id = face_identity_face."assetFaceId"
      INNER JOIN filtered_assets ON filtered_assets.id = asset_face."assetId"
    WHERE
      asset_face."deletedAt" IS NULL
      AND asset_face."isVisible" = true
  ),
  profiles AS (
    SELECT
      'user-person'::text AS "profileType",
      person.id AS "profileId",
      NULL::uuid AS "spaceId",
      person."identityId",
      person.name,
      person."isHidden",
      person."updatedAt",
      0 AS "profileRank"
    FROM
      person
    WHERE
      person."ownerId" = $6
      AND person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          identity_faces
        WHERE
          identity_faces."identityId" = person."identityId"
      )
    UNION ALL
    SELECT
      'space-person'::text AS "profileType",
      shared_space_person.id AS "profileId",
      shared_space_person."spaceId",
      shared_space_person."identityId",
      COALESCE(
        NULLIF(shared_space_person_alias.alias, ''),
        shared_space_person.name,
        ''
      ) AS name,
      shared_space_person."isHidden",
      shared_space_person."updatedAt",
      CASE
        WHEN NULLIF(shared_space_person_alias.alias, '') IS NULL THEN 2
        ELSE 1
      END AS "profileRank"
    FROM
      shared_space_person
      LEFT JOIN shared_space_person_alias ON shared_space_person_alias."personId" = shared_space_person.id
      AND shared_space_person_alias."userId" = $7
    WHERE
      shared_space_person."spaceId" = any ($8::uuid[])
      AND shared_space_person."identityId" IS NOT NULL
      AND EXISTS (
        SELECT
          1
        FROM
          shared_space_person_face
          INNER JOIN asset_face AS profile_face ON profile_face.id = shared_space_person_face."assetFaceId"
        WHERE
          shared_space_person_face."personId" = shared_space_person.id
          AND profile_face."deletedAt" IS NULL
          AND profile_face."isVisible" = true
      )
      AND EXISTS (
        SELECT
          1
        FROM
          identity_faces
        WHERE
          identity_faces."identityId" = shared_space_person."identityId"
      )
  ),
  ranked_profiles AS (
    SELECT
      profiles.*,
      row_number() OVER (
        PARTITION BY
          profiles."identityId"
        ORDER BY
          NULLIF(profiles.name, '') IS NULL,
          profiles."profileRank",
          lower(profiles.name),
          profiles."updatedAt" DESC,
          profiles."profileId"
      ) AS display_rn,
      row_number() OVER (
        PARTITION BY
          profiles."identityId"
        ORDER BY
          CASE
            WHEN profiles."profileType" = 'user-person' THEN 0
            ELSE profiles."profileRank"
          END,
          NULLIF(profiles.name, '') IS NULL,
          lower(profiles.name),
          profiles."updatedAt" DESC,
          profiles."profileId"
      ) AS primary_rn
    FROM
      profiles
    WHERE
      profiles."isHidden" = false
  )
SELECT
  CASE
    WHEN primary_profiles."profileType" = 'space-person' THEN 'space-person:' || primary_profiles."profileId"::text
    ELSE 'person:' || primary_profiles."profileId"::text
  END AS id,
  COALESCE(
    NULLIF(display_profiles.name, ''),
    primary_profiles.name,
    ''
  ) AS name,
  primary_profiles."profileType",
  primary_profiles."profileId",
  primary_profiles."spaceId"
FROM
  ranked_profiles AS primary_profiles
  INNER JOIN ranked_profiles AS display_profiles ON display_profiles."identityId" = primary_profiles."identityId"
  AND display_profiles.display_rn = 1
WHERE
  primary_profiles.primary_rn = 1
ORDER BY
  NULLIF(
    COALESCE(
      NULLIF(display_profiles.name, ''),
      primary_profiles.name,
      ''
    ),
    ''
  ) IS NULL,
  lower(
    COALESCE(
      NULLIF(display_profiles.name, ''),
      primary_profiles.name,
      ''
    )
  ),
  primary_profiles."profileId"
select distinct
  "rating"
from
  "asset_exif"
where
  "assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
  and "rating" is not null
  and "rating" > $7
order by
  "rating"
select distinct
  "type"
from
  "asset"
where
  "id" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."visibility" = $1
      and "asset"."deletedAt" is null
      and (
        "asset"."ownerId" = any ($2::uuid[])
        or exists (
          select
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($3::uuid[])
        )
        or exists (
          select
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($4::uuid[])
        )
      )
      and "asset"."fileCreatedAt" >= $5
      and exists (
        select
        from
          "asset_face"
          inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "face_identity_face"."identityId" = $6::uuid
      )
  )
order by
  "type"
select
  "id",
  "expiresAt",
  "pinExpiresAt"
from
  "session"
where
  "id" = $1

-- SessionRepository.isPendingSyncReset
select
  "isPendingSyncReset"
from
  "session"
where
  "id" = $1

-- SessionRepository.getByToken
select
  "session"."id",
  "session"."updatedAt",
  "session"."pinExpiresAt",
  "session"."appVersion",
  (
    select
      to_json(obj)
    from
      (
        select
          "user"."id",
          "user"."name",
          "user"."email",
          "user"."isAdmin",
          "user"."quotaUsageInBytes",
          "user"."quotaSizeInBytes"
        from
          "user"
        where
          "user"."id" = "session"."userId"
          and "user"."deletedAt" is null
      ) as obj
  ) as "user"
from
  "session"
where
  "session"."token" = $1
  and (
    "session"."expiresAt" is null
    or "session"."expiresAt" > $2
  )

-- SessionRepository.getByUserId
select
  "session".*
from
  "session"
  inner join "user" on "user"."id" = "session"."userId"
  and "user"."deletedAt" is null
where
  "session"."userId" = $1
  and (
    "session"."expiresAt" is null
    or "session"."expiresAt" > $2
  )
order by
  "session"."updatedAt" desc,
  "session"."createdAt" desc

-- SessionRepository.delete
delete from "session"
where
  "id" = $1::uuid

-- SessionRepository.invalidateAll
delete from "session"
where
  "userId" = $1
  and "id" != $2

-- SessionRepository.lockAll
update "session"
set
  "pinExpiresAt" = $1
where
  "userId" = $2

-- SessionRepository.resetSyncProgress
begin
update "session"
set
  "isPendingSyncReset" = $1
where
  "id" = $2
delete from "session_sync_checkpoint"
where
  "sessionId" = $1
rollback
