import { ImportManager, ImportStep } from '$lib/managers/import-manager.svelte';
import type { TakeoutAlbum } from '$lib/utils/google-takeout-parser';

function makeFile(name: string, size: number): File {
  return new File([new ArrayBuffer(size)], name);
}

function makeAlbum(name: string, opts: Partial<TakeoutAlbum> = {}): TakeoutAlbum {
  return {
    name,
    itemCount: opts.itemCount ?? 3,
    isAutoGenerated: opts.isAutoGenerated ?? false,
    itemPaths: opts.itemPaths ?? [],
  };
}

describe('ImportManager', () => {
  let manager: ImportManager;

  beforeEach(() => {
    vi.resetAllMocks();
    manager = new ImportManager();
  });

  describe('step navigation', () => {
    it('starts at Files step', () => {
      expect(manager.currentStep).toBe(ImportStep.Files);
    });

    it('nextStep advances to the next step', () => {
      manager.nextStep();
      expect(manager.currentStep).toBe(ImportStep.Scan);
      manager.nextStep();
      expect(manager.currentStep).toBe(ImportStep.Review);
    });

    it('previousStep goes back', () => {
      manager.nextStep();
      manager.nextStep();
      expect(manager.currentStep).toBe(ImportStep.Review);
      manager.previousStep();
      expect(manager.currentStep).toBe(ImportStep.Scan);
    });

    it("doesn't go back past Files", () => {
      manager.previousStep();
      expect(manager.currentStep).toBe(ImportStep.Files);
    });

    it("doesn't go past Import", () => {
      for (let i = 0; i < 10; i++) {
        manager.nextStep();
      }
      expect(manager.currentStep).toBe(ImportStep.Import);
    });

    it('reset returns to Files', () => {
      manager.nextStep();
      manager.nextStep();
      manager.addFiles([makeFile('a.zip', 100)]);
      manager.reset();
      expect(manager.currentStep).toBe(ImportStep.Files);
      expect(manager.selectedFiles).toHaveLength(0);
    });
  });

  describe('file management', () => {
    it('starts with no files', () => {
      expect(manager.selectedFiles).toHaveLength(0);
    });

    it('addFiles adds files', () => {
      const files = [makeFile('a.zip', 100), makeFile('b.zip', 200)];
      manager.addFiles(files);
      expect(manager.selectedFiles).toHaveLength(2);
      expect(manager.selectedFiles[0].name).toBe('a.zip');
    });

    it('addFiles appends to existing files', () => {
      manager.addFiles([makeFile('a.zip', 100)]);
      manager.addFiles([makeFile('b.zip', 200)]);
      expect(manager.selectedFiles).toHaveLength(2);
    });

    it('clearFiles empties the list', () => {
      manager.addFiles([makeFile('a.zip', 100)]);
      manager.clearFiles();
      expect(manager.selectedFiles).toHaveLength(0);
    });

    it('calculates totalSize', () => {
      manager.addFiles([makeFile('a.zip', 100), makeFile('b.zip', 250)]);
      expect(manager.totalSize).toBe(350);
    });

    it('totalSize is 0 with no files', () => {
      expect(manager.totalSize).toBe(0);
    });
  });

  describe('album management', () => {
    it('toggleAlbum toggles selection', () => {
      manager.toggleAlbum('Vacation');
      expect(manager.selectedAlbums.has('Vacation')).toBe(true);
      manager.toggleAlbum('Vacation');
      expect(manager.selectedAlbums.has('Vacation')).toBe(false);
    });

    it('setAlbums selects non-auto-generated albums by default', () => {
      const albums: TakeoutAlbum[] = [
        makeAlbum('Vacation'),
        makeAlbum('Photos from 2023', { isAutoGenerated: true }),
        makeAlbum('Family Trip'),
      ];
      manager.setAlbums(albums);
      expect(manager.selectedAlbums.has('Vacation')).toBe(true);
      expect(manager.selectedAlbums.has('Family Trip')).toBe(true);
      expect(manager.selectedAlbums.has('Photos from 2023')).toBe(false);
    });

    it('selectAllAlbums selects all albums from scanResult', () => {
      const albums: TakeoutAlbum[] = [makeAlbum('Vacation'), makeAlbum('Photos from 2023', { isAutoGenerated: true })];
      manager.scanResult = {
        items: [],
        albums,
        stats: { totalMedia: 0, withLocation: 0, withDate: 0, favorites: 0, archived: 0, dateRange: undefined },
      };
      manager.selectAllAlbums();
      expect(manager.selectedAlbums.has('Vacation')).toBe(true);
      expect(manager.selectedAlbums.has('Photos from 2023')).toBe(true);
    });

    it('deselectAllAlbums clears selection', () => {
      manager.toggleAlbum('Vacation');
      manager.toggleAlbum('Work');
      manager.deselectAllAlbums();
      expect(manager.selectedAlbums.size).toBe(0);
    });

    it('selectAllAlbums is a no-op when scanResult is undefined', () => {
      manager.selectAllAlbums();
      expect(manager.selectedAlbums.size).toBe(0);
    });
  });

  describe('import options', () => {
    it('has sensible defaults', () => {
      expect(manager.options.importFavorites).toBe(true);
      expect(manager.options.importArchived).toBe(true);
      expect(manager.options.importDescriptions).toBe(true);
      expect(manager.options.skipDuplicates).toBe(true);
    });
  });

  describe('import progress tracking', () => {
    it('starts with all zeros', () => {
      expect(manager.importProgress.imported).toBe(0);
      expect(manager.importProgress.skipped).toBe(0);
      expect(manager.importProgress.errors).toBe(0);
      expect(manager.importProgress.total).toBe(0);
      expect(manager.importProgress.currentFile).toBe('');
      expect(manager.importProgress.currentAlbum).toBe('');
      expect(manager.importProgress.albumsCreated).toBe(0);
      expect(manager.importProgress.errorLog).toHaveLength(0);
    });
  });

  describe('pause state', () => {
    it('starts not paused', () => {
      expect(manager.isPaused).toBe(false);
    });

    it('togglePause toggles pause state', () => {
      manager.togglePause();
      expect(manager.isPaused).toBe(true);
      manager.togglePause();
      expect(manager.isPaused).toBe(false);
    });
  });

  describe('reset', () => {
    it('resets all state to initial values', () => {
      // Modify everything
      manager.nextStep();
      manager.nextStep();
      manager.addFiles([makeFile('a.zip', 100)]);
      manager.scanResult = {
        items: [],
        albums: [makeAlbum('Test')],
        stats: { totalMedia: 0, withLocation: 0, withDate: 0, favorites: 0, archived: 0, dateRange: undefined },
      };
      manager.toggleAlbum('Test');
      manager.options.importFavorites = false;
      manager.importProgress.imported++;
      manager.importProgress.errorLog.push({ file: 'f.jpg', error: 'err' });
      manager.togglePause();

      manager.reset();

      expect(manager.currentStep).toBe(ImportStep.Files);
      expect(manager.selectedFiles).toHaveLength(0);
      expect(manager.scanResult).toBeUndefined();
      expect(manager.selectedAlbums.size).toBe(0);
      expect(manager.options.importFavorites).toBe(true);
      expect(manager.importProgress.imported).toBe(0);
      expect(manager.importProgress.errorLog).toHaveLength(0);
      expect(manager.isPaused).toBe(false);
      expect(manager.isComplete).toBe(false);
    });
  });
});
