// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class LiveTextPigeonCodecReader: FlutterStandardReader {
}

private class LiveTextPigeonCodecWriter: FlutterStandardWriter {
}

private class LiveTextPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LiveTextPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LiveTextPigeonCodecWriter(data: data)
  }
}

class LiveTextPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LiveTextPigeonCodec(readerWriter: LiveTextPigeonCodecReaderWriter())
}

/// iOS-only. VisionKit Live Text is not available on Android, so this API
/// intentionally has no Kotlin counterpart; callers must gate on
/// `CurrentPlatform.isIOS` before invoking it.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LiveTextHostApi {
  /// True only when the OS is iOS 16+ *and* `ImageAnalyzer.isSupported`.
  func isSupported() throws -> Bool
  /// Where the image sits inside the platform view, in unit coordinates.
  func setContentsRect(viewId: Int64, left: Double, top: Double, width: Double, height: Double) throws
  /// Fetch (from the shared authenticated URLCache) and analyse the image.
  func loadImage(viewId: Int64, url: String) throws
  /// Drop the analysis and clear any active selection.
  func dispose(viewId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LiveTextHostApiSetup {
  static var codec: FlutterStandardMessageCodec { LiveTextPigeonCodec.shared }
  /// Sets up an instance of `LiveTextHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LiveTextHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// True only when the OS is iOS 16+ *and* `ImageAnalyzer.isSupported`.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.LiveTextHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// Where the image sits inside the platform view, in unit coordinates.
    let setContentsRectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.LiveTextHostApi.setContentsRect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setContentsRectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let leftArg = args[1] as! Double
        let topArg = args[2] as! Double
        let widthArg = args[3] as! Double
        let heightArg = args[4] as! Double
        do {
          try api.setContentsRect(viewId: viewIdArg, left: leftArg, top: topArg, width: widthArg, height: heightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setContentsRectChannel.setMessageHandler(nil)
    }
    /// Fetch (from the shared authenticated URLCache) and analyse the image.
    let loadImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.LiveTextHostApi.loadImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let urlArg = args[1] as! String
        do {
          try api.loadImage(viewId: viewIdArg, url: urlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadImageChannel.setMessageHandler(nil)
    }
    /// Drop the analysis and clear any active selection.
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.LiveTextHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          try api.dispose(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LiveTextFlutterApiProtocol {
  /// Reports whether the analysis found any text, so Flutter can fall back to
  /// the server-OCR overlay when Live Text finds nothing.
  func onAnalysisComplete(viewId viewIdArg: Int64, hasText hasTextArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Reports whether a text selection is currently live.
  ///
  /// Flutter only hands the native view the pointers that land on text, so that
  /// pinch/pan/page-swipe keep working everywhere else. Selection handles and
  /// the callout sit *outside* the text quads, so while a selection exists
  /// Flutter has to concede every pointer instead.
  func onSelectionActiveChanged(viewId viewIdArg: Int64, active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LiveTextFlutterApi: LiveTextFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LiveTextPigeonCodec {
    return LiveTextPigeonCodec.shared
  }
  /// Reports whether the analysis found any text, so Flutter can fall back to
  /// the server-OCR overlay when Live Text finds nothing.
  func onAnalysisComplete(viewId viewIdArg: Int64, hasText hasTextArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.LiveTextFlutterApi.onAnalysisComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([viewIdArg, hasTextArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Reports whether a text selection is currently live.
  ///
  /// Flutter only hands the native view the pointers that land on text, so that
  /// pinch/pan/page-swipe keep working everywhere else. Selection handles and
  /// the callout sit *outside* the text quads, so while a selection exists
  /// Flutter has to concede every pointer instead.
  func onSelectionActiveChanged(viewId viewIdArg: Int64, active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.LiveTextFlutterApi.onSelectionActiveChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([viewIdArg, activeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
